export const INCREASE = 'INCREASE'
export const DECREASE = 'DECREASE'
export const title = 'title'
export const personnlFilter = 'personnlFilter'
export const signupStartTime = 'signupStartTime'
export const signupEndTime = 'signupEndTime'
export const examCodeStatus = 'examCodeStatus'
